version: '3'
services:
  # Elasticsearch 服务
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # 配置 Elasticsearch 的 JVM 内存
    ports:
      - "9200:9200"  # Elasticsearch HTTP 服务端口
      - "9300:9300"  # Elasticsearch TCP 协议端口
    volumes:
      - esdata:/usr/share/elasticsearch/data  # 持久化 Elasticsearch 数据
    networks:
      - skywalking-network
    restart: always

  # SkyWalking OAP（后台分析服务）
  skywalking-oap:
    image: apache/skywalking-oap-server:9.7.0-java17
    container_name: skywalking-oap
    environment:
      - SW_OAP_STORAGE=elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200  # Elasticsearch 服务地址
      - SW_STORAGE_ES_INDEX_PREFIX=skywalking  # SkyWalking 数据索引前缀
      - SW_OAP_HTTP_PORT=12800  # OAP 服务的 HTTP 端口
      - SW_OAP_GRPC_PORT=11800  # OAP 服务的 gRPC 端口
    ports:
      - "12800:12800"  # OAP HTTP 服务端口
      - "11800:11800"  # OAP gRPC 服务端口
    depends_on:
      - elasticsearch  # SkyWalking OAP 在 Elasticsearch 服务启动后启动
    networks:
      - skywalking-network
    restart: always

  # SkyWalking UI（前端展示服务）
  skywalking-ui:
    image: apache/skywalking-ui:9.7.0-java17
    container_name: skywalking-ui
    environment:
      - SW_OAP_ADDRESS=http://skywalking-oap:12800  # OAP 服务地址
    ports:
      - "8080:8080"  # UI 服务端口
    depends_on:
      - skywalking-oap  # SkyWalking UI 在 OAP 服务启动后启动
    networks:
      - skywalking-network
    restart: always

networks:
  skywalking-network:
    driver: bridge

volumes:
  esdata:
    driver: local
